language: python

matrix:
  include:
    - env: ES_APT_URL=https://packages.elastic.co/elasticsearch/2.x/debian ES_DSL_VERS=2.2.0 ES_VERS=2.2.1
      python: 3.7
      sudo: true
      dist: bionic
    - env: ES_APT_URL=https://artifacts.elastic.co/packages/7.x/apt ES_DSL_VERS=7.2.1 ES_VERS=7.8.0
      python: 3.7
      dist: bionic
      sudo: true
    - env: ES_APT_URL=https://packages.elastic.co/elasticsearch/2.x/debian ES_DSL_VERS=2.2.0 ES_VERS=2.2.1
      python: 3.8
      sudo: true
      dist: bionic
    - env: ES_APT_URL=https://artifacts.elastic.co/packages/7.x/apt ES_DSL_VERS=7.2.1 ES_VERS=7.8.0
      python: 3.8
      dist: bionic
      sudo: true
    - env: ES_APT_URL=https://artifacts.elastic.co/packages/7.x/apt ES_DSL_VERS=7.2.1 ES_VERS=7.8.0
      python: 3.9
      dist: bionic
      sudo: true
    - env: ES_APT_URL=https://artifacts.elastic.co/packages/6.x/apt ES_DSL_VERS=6.3.1 ES_VERS=6.4.3
      python: 3.10
      dist: bionic
      sudo: true
    - env: ES_APT_URL=https://artifacts.elastic.co/packages/7.x/apt ES_DSL_VERS=7.2.1 ES_VERS=7.8.0
      python: 3.10
      dist: bionic
      sudo: true


before_install:
  - sudo rm /etc/apt/sources.list; sudo touch /etc/apt/sources.list
  - wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  - echo "deb $ES_APT_URL stable main" | sudo tee -a /etc/apt/sources.list.d/elastic.list
  - sudo apt-get update && sudo apt-get install elasticsearch=$ES_VERS -y --allow-downgrades
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch 
  - sudo systemctl start elasticsearch.service
  - while ! curl -XGET "localhost:9200";do sleep 1; done
  - curl localhost:9200

install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip install coveralls
  - pip install elasticsearch-dsl==$ES_DSL_VERS

script:
  - make tests
  - make quality

after_success:
  # coveralls only for python3.8 and ES 7
  -  python --version |grep 3.8 && [ $ES_DSL_VERS == "7.2.1" ] && coveralls
